baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'PaperFE Example Site'
theme = ['github.com/adityatelange/hugo-PaperMod']

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.125.7"
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
